version: '3.8'

services:
  ras-run:
    container_name: ras-run
    build:
      context: .
      dockerfile: Dockerfile-alt
    volumes:
      - ./:/app
    env_file:
      - ./.env
    entrypoint: |
      /src/go/bin/CompileDaemon --build="go build main.go" --command="./main -payload=runs/realization_1/event_1/payload.yml"
    # entrypoint: sleep 1d
