version: '3.8'

services:
  ras-run:
    container_name: ras-run
    # platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./.env
    # entrypoint: sleep 1d
    entrypoint: ./main
